### PR TITLE
all.po

### PR DESCRIPTION
**Pull request by Tobias-B-Besemer**

### CODE REVIEW

**Comment by Tobias-B-Besemer** [comment]
Latest POs extracted from Launchpad

**Comment by az0** [comment]
Thanks, but I use this script to attribute credit to translator authors

https://github.com/bleachbit/bleachbit-misc/blob/master/lp2git.py

**Comment by Tobias-B-Besemer** [comment]
But you will use all the updated POs ???

**Comment by Tobias-B-Besemer** [comment]
That 20.000+ new lines translations...

**Comment by az0** [comment]
Many of the line changes are not new translations. Many are just new references to files and line numbers. Example: here https://github.com/bleachbit/bleachbit/pull/520/files#diff-747a382b7fd38ecfd6893ac4fcf3f98dL205

Today I updated German and French, and this should bring them all up to date. If I missed any, let me know. Also, feel free to use the lp2git script yourself, if you want.

**Comment by Tobias-B-Besemer** [comment]
Mhhmmm... If I wouldn't be busy all the time with writing cleaners, my new Linux machine would be ready already... :-D

**Pull request closed without merging**
