### PR TITLE
Close running applications

### PR DESCRIPTION
**Pull request by brahmastra2016**
Added User select able option to close running application.

Default= “NO”

### CODE REVIEW

**Comment by ROCKNROLLKID** [comment]
This might be nice to have for Windows, too, especially when cleaning browsers. Looks good otherwise, thought I don't own a Mac to actually test this.

**Comment by az0** [comment]
@ROCKNROLLKID 
The title says "Mac" but the code has paths for all operating systems. 

@brahmastra2016 
Thank you for working on this! It does seem useful. 

The major things I see now are
1.  Checking the command line arguments for `--preset` is not a reliable way to detect command line mode. For example, command line mode can be run with just `bleachbit --preview google_chrome.cache`. 

The heuristic I see is: if there are zero command line arguments, it is GUI mode. If the command line has --gui, it is GUI. Otherwise it is CLI. 

Rather than code this rule many places, there should be a standard way. One option is to create a new function, like in `bleachbit/__init__..py`. Another option is setting a variable in that module.

2. There are two kinds of command line mode. If there is no terminal, such as when the application is invoked from cron, then the application should not prompt with a question because there cannot be a response. I think `sys.stdout.isatty()` is the right way to check.

My lesser-important feedback: There are many nested conditions and much similarity between operating systems, so refactoring would make this look cleaner and shorter.

**Comment by brahmastra2016** [comment]
I haved added it for windows too , just forgot to mention it.

**Comment by ROCKNROLLKID** [comment]
I feel like closing ALL running applications might be too aggressive. What if we just limited this to web browsers? That seems like it is the only time we really need to close any applications is when we are cleaning web browsers.

**Comment by brahmastra2016** [comment]
That is a good suggestion,  i am planning to put some time into this project.been off for a while now.
--
Sent from myMail for Android Friday, 15 December 2017, 05:33PM -05:00 from Alex  notifications@github.com :

**Comment by ROCKNROLLKID** [comment]
Another theory I had is to do what CCleaner does and just notify the user that a browser is running and ask if BleachBit should terminate the process. This is probably the best way to do this.

**Comment by brahmastra2016** [comment]
That is what my current code does it prompt user if they wish to close the app or continue  without closing.
--
Sent from myMail for Android Wednesday, 20 December 2017, 09:12PM -05:00 from Alex  notifications@github.com :

**Comment by az0** [comment]
This is an interesting PR, so I hope you can please make a few adjustments in response to my comment https://github.com/bleachbit/bleachbit/pull/213#issuecomment-293766999 dated April 12. Until then, I will close it.

**Pull request closed without merging**
