### PR TITLE
Add gspawn-win32-helper.exe for opening external URLs (About dialog)

### LINKED ISSUE #918: Website button fails
Button in "about BleachBit" that's supposed to link to the BleachBit website doesn't work, screenshot below ...
Annotation 2020-05-10 132313

### PR DESCRIPTION
**Pull request by mkhon**
Fixes #918

### CODE REVIEW

**Comment by az0** [comment]
I downloaded `BleachBit-4.0.1.1650-portable.zip` and unpacked on a machine without a development environment. I confirmed it has the file `gspawn-win32-helper.exe`, but I still get the error "No application is registered as handling this file."

**Comment by mkhon** [comment]
Original report was about "Failed to execute helper program" - this PR fixes this error.
I'll check "No application is registered as handling this file" error.

**Comment by mkhon** [comment]
I think the PR can be safely merged as it fixes original issue.

**Comment by mkhon** [comment]
I noticed two things:
- one more helper (gspawn-win32-helper-console.exe) is required for bleachbit_console.exe
- "No application is registered as handling this file" occurs when default web browser is Microsoft Edge. If I set it to Chrome or Internet Explorer (11) urls are opened as expected - this seems to be a bug in GTK+ and I'd suggest to open a separate bug about this (which will hopefully be fixed with GTK+ update)

**Comment by az0** [comment]
Yes, I see the same thing: with Edge, there is "no application is registered." With Google Chrome, it opens the URL.

**Pull request merged**
