### PR TITLE
add dnf clean package-cache support

### PR DESCRIPTION
**Pull request by klslz**
I introduced  dnf  clean package-cache support. I tested it on Fedora31.
I basically took yum entries as reference.

### CODE REVIEW

**Comment by az0** [comment]
@klslz The changes look good! 

The .po changes are unnecessary because they are automatically generated. I generate a bleachbit.pot file, upload it to Launchpad, then translatators translate it, and I download the .po files. Two options: you remove the .po files from your commit to make it simpler, or I merge it as is. Either is OK. Let me know.

**Comment by az0** [comment]
Would you be interested in also fixing https://github.com/bleachbit/bleachbit/issues/306 (DNF autoremove)?

**Comment by az0** [comment]
As a follow up to your change here, I added dnf.xml in commit https://github.com/bleachbit/bleachbit/commit/b692b2163e22c56facef72d4ac1463857e6c7bc1 . Perhaps you could test this.

**Comment by klslz** [comment]
Hmmh. I didn't realize  dnf.xml wasn't uploaded. I did introduce it on my side and tested with it.

**Comment by klslz** [comment]
I'll have a look at dnf autoremove.

**Pull request merged**
