### PR TITLE
Update the forgotten NsisMultiUser-Plugins

### PR DESCRIPTION
**Pull request by Tobias-B-Besemer**

### CODE REVIEW

**Comment by az0** [comment]
Is this verbatim from https://github.com/Drizin/NsisMultiUser/tree/master/Plugins/x86-unicode ?

**Comment by Tobias-B-Besemer** [comment]
Yes! ANSI & Unicode!

**Comment by Tobias-B-Besemer** [comment]
Guess the envelop prob comes from there, 'cause there was a Win10 improvement for the latest Win10 builds in StdUtils.dll, if you follow upstream...

**Comment by Tobias-B-Besemer** [comment]
Don't understand the code really, but IMHO it looks promising...
https://github.com/lordmulder/stdutils/commit/79cd433b9ab628b4210e4eef0e73c22bb887507a
...and ATM you use the latest StdUtils.nsh but the wrong DLL to it... :-/

**Pull request merged**
