### PR TITLE
Python 3

### PR DESCRIPTION
**Pull request by mkhon**
- fix py2exe
- fix localization

### CODE REVIEW

**Comment by az0** [comment]
AppVeyor is stuck here: "test_preferences (tests.TestGUI.GUITestCase)"

I made a fix for this on the master branch. I could merge master into py3, or you could.

**Comment by mkhon** [comment]
I noticed that but I do not know how to abort AppVeyor job.

I think it is stuck because of "new version" dialog opened up. I fixed this in python3 branch.

**Comment by az0** [comment]
Great to see more progress. 

When I tried a basic smoke test, I came into problems. Would you please check into these issues?

https://github.com/bleachbit/bleachbit/issues/757

https://github.com/bleachbit/bleachbit/issues/758

https://github.com/bleachbit/bleachbit/issues/759

**Comment by mkhon** [comment]
I think #757 and probably also #759 are invalid.

**Comment by mkhon** [comment]
#758 should be fixed in the new PR.

**Comment by az0** [comment]
Please also take a look at 
https://github.com/bleachbit/bleachbit/issues/761
https://github.com/bleachbit/bleachbit/issues/760

I'll merge what you have so far

**Pull request merged**
