### PR TITLE
Make REMOVESELF delete the top-folder even with a globbed path

### PR DESCRIPTION
**Pull request by livingentity**
REMOVESELF is supposed to delete both the content and the top-folder. However though it succeeds for the content it currently fails to delete the _top-folder if it's path has a glob in it_. This commit fixes that.

### CODE REVIEW

**Comment by livingentity** [comment]
I now tested it on _all_ entries with REMOVESELF in the current winapp2.ini and it works fine.

However I identified a new problem:
If a folder isn't empty (e.g. because you only cleaned *.log but there are also other files or subfolders) it doesn't get deleted.

What do we want in this case? Don't know how CCleaner handles this.

Apart from that this commit should be ready to merge I guess.

**Comment by az0** [comment]
FYI I started writing some unit tests for this. 

It's the folder is not empty, then it should not be deleted. Let's assume this until we can confirm otherwise.

**Comment by livingentity** [comment]
Thank you.
Which variant do we want, commit 1 or 2? The 2nd one adds an additional `type="d"` for `search="file"` which isn't really needed but it shortens the code unless this causes a performance issue.

**Comment by az0** [comment]
This is a [new test for REMOVESELF](https://github.com/bleachbit/bleachbit/commit/dfb4e08d05b07ffd6edd6802e03254a4b8fe236a), but it passes without the new code in this pull request. Even if you can't code it, please describe a test that is missing that would fail without the new code.

**Comment by livingentity** [comment]
For safety I downloaded 4.4.1.2009, tried it and it does not remove folders whenever a glob is somewhere in the directory path, as expected.

Your test cases seem to be correct and should fail. I cannot easily tell why they pass, I would first need to learn how this works exactly.

**Comment by livingentity** [comment]
Tried to fix [here](https://github.com/bleachbit/bleachbit/pull/1252).

**Comment by az0** [comment]
> Tried to fix [here](https://github.com/bleachbit/bleachbit/pull/1252).

Thanks. Hmm, they are still passing.

For troubleshooting, can you suggest a section from Winapp2.ini to manually test?

**Comment by az0** [comment]
Test did fail https://ci.appveyor.com/project/az0/bleachbit/builds/40469743#L2281

```
FAIL: test_removeself (tests.TestWinapp.WinappTestCase)
Test for the removeself option
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\bleachbit\tests\TestWinapp.py", line 491, in test_removeself
    self.assertNotExists(fn, filekey)
  File "C:\projects\bleachbit\tests\common.py", line 122, in assertNotExists
    'The file %s should not exist, but it does. %s' % (path, msg))
AssertionError: The file C:\Users\appveyor\AppData\Local\Temp\1\WinappTestCaseqjr44qp8\dir_c\subdir\foo.log should not exist, but it does. FileKey1=C:\Users\appveyor\AppData\Local\Temp\1\WinappTestCaseqjr44qp8\dir_a\sub*|*.*|REMOVESELF
----------------------------------------------------------------------
Ran 213 tests in 119.046s
FAILED (failures=1, skipped=34)
```

I will take a closer look

**Comment by livingentity** [comment]
Yes, but that's just me being stupid. It shouldn't fail because of a file but because the top folder isn't deleted.

**Comment by livingentity** [comment]
@rados
Just to rule out an isolated issue on my system, can you reproduce this (directly in BleachBit, I mean)? Please just take one entry of the winapp2.ini with REMOVESELF and a glob in the path, e.g. `%LocalAppData%\Google\Chrome*\Application\SetupMetrics|*.*|REMOVESELF` and check if the top-folder, i.e. SetupMetrics, gets deleted.

**Comment by rados** [comment]
> @rados
> Just to rule out an isolated issue on my system, can you reproduce this (directly in BleachBit, I mean)? Please just take one entry of the winapp2.ini with REMOVESELF and a glob in the path, e.g. `%LocalAppData%\Google\Chrome*\Application\SetupMetrics|*.*|REMOVESELF` and check if the top-folder, i.e. SetupMetrics, gets deleted.

Yes it gets deleted.

**Comment by livingentity** [comment]
Thanks for testing. To double check: Even without my commit it's deleted?

**Comment by rados** [comment]
No, before the fix those with '*' in the path are not deleted.

**Comment by livingentity** [comment]
Awesome. I already thought I lost my mind because andrew's tests suggest otherwise. Have a virtual beer. Cheers!

**Pull request merged**
