### PR TITLE
Fix app menu translation

### LINKED ISSUE #564: application menu is not translated
Command run on Ubuntu 19.04
`LANG=es_MX.UTF-8 python bleachbit.py`

Screenshot from 2019-06-06 21-58-26 menu translation

### PR DESCRIPTION
**Pull request by mkhon**
Fixes #564

### CODE REVIEW

**Comment by az0** [comment]
Yesterday I tested on Ubuntu using the command ` LANG=es_MX.UTF-8 python
bleachbit.py` from the source directory after running `make -C po local` to
build the translations.

I got the same results as the screenshot in the issue ticket: most parts
such as the tree view are translated, but the menu is not translated.

I think the issue is that libintl looks for translations in a different
path than gettext.

**Comment by mkhon** [comment]
Andrew,

Have you run 'dpkg-reconfigure locales' and selected es_MX there? Without
doing this gettext() will not work (and I suppose there is an error message
in the console about that - please provide console output).

Max

**Comment by az0** [comment]
Originally I had this error when changing the locale
```
Gtk-WARNING **: Locale not supported by C library.
    Using the fallback 'C' locale.
````

Then I ran
```
sudo apt-get install language-pack-en-base,
sudo dpkg-reconfigure locales
export LC_ALL="es_MX.UTF-8"
```
This clears up the "locale not supported" error message, and the menu is translated.

I'd like to confirm it works on Windows too (for any non-English language). If you have a screenshot, that would work. Otherwise, I will try soon.

**Comment by mkhon** [comment]
Andrew,

I verified this on Windows with non-English language. I will be able to
upload screenshot only on Mon/Tue (out of coverage area for a weekend).

Max

**Comment by mkhon** [comment]
Screen Shot 2019-07-23 at 11 18 16
Screenshot from Windows 10 (Russian locale) is attached.

**Comment by az0** [comment]
It looks great on your system. You are running from source (without installation or py2exe building), right? 

I set up a clean Windows 10 May 2019 Edition machine. The install and setup was Spanish, and the operating system UI is all Spanish.

Then I downloaded the BleachBit portable from [AppVeyor build 2.3.1141](https://ci.appveyor.com/project/az0/bleachbit/builds/26044374/artifacts). The general BleachBit UI is Spanish, but the app menu is still English. I confirmed its Git commit bab75a46 .

Here's a screenshot
2019-07-23 app menu English

**Comment by mkhon** [comment]
@az0 in case of portable "locale_dir" is a Unicode string which libintl.bindtextdomain() can not handle.
I pushed a new version with a fix for that (which will work for ASCII-only bleachbit paths, but bleachbit can not be run from Unicode path anyway).

**Comment by az0** [comment]
I pulled your PR into a new branch temporarily. I merged in your auto start fix, and I tested the [build 2.3.1171](https://ci.appveyor.com/project/az0/bleachbit/builds/26255152). I tried the ASCII path `c:\bb\`  for porable mode, and app menu translation is not working  in portable mode. I installed tried installation, and the app menu is still not translated.

**Comment by mkhon** [comment]
@az0 your branch is not in sync with mine.

I have the following code in my branch (which was force-pushed because I squashed the commits):

            # bindtextdomain can not handle Unicode
            if isinstance(locale_dir, unicode):
                path = locale_dir.encode('utf-8')
            else:
                path = locale_dir
            libintl.bindtextdomain('bleachbit', path)
            libintl.bind_textdomain_codeset('bleachbit', 'UTF-8')

**Comment by az0** [comment]
I confirm the fix on Windows 10 (Spanish). I tested installed and porable mode.

Thank you, Max!

**Pull request merged**
