### PR TITLE
Do not delete bookmarked domain level favicons in firefox.

### PR DESCRIPTION
**Pull request by rados**

### CODE REVIEW

**Comment by abitrolly** [comment]
And if I want to erase full history?

**Comment by rados** [comment]
> And if I want to erase full history?

Good question. Probably we could have new action: 'Full URL history'? The current one is named only: 'URL history'.

**Comment by abitrolly** [comment]
Or add separate `Clean Bookmarks`.

**Comment by XhmikosR** [comment]
@rados I just tested this on my VM and seems to work fine. Is there something else preventing this to land?

**Comment by eleius** [comment]
> @rados I just tested this on my VM and seems to work fine.

It works on my system too.

**Comment by eleius** [comment]
@az0 could you please merge this fix for next release?

**Review by naxl — APPROVED** [review]

**Pull request merged**
