### PR TITLE
Add installation instructions and prerequisites to README

### PR DESCRIPTION
**Pull request by Huluti**
In order to simplify installation and building from source.

### CODE REVIEW

**Comment by az0** [comment]
How about instead a link to the [installation documentation](https://docs.bleachbit.org/doc/install-on-linux.html)? It's more thorough. Also, the documentation directly contradicts what you wrote. The documentation states:

>Installing using apt from the distribution’s repositories is not recommended because they tend to carry old releases of BleachBit.

But I would be willing to expand the documentation to include the system repository methods, like you wrote, so the user has a choice.

(The documentation is also a Git repository, by the way.)

**Comment by Huluti** [comment]
As you want, even though I think it's easier for users to use packages than go through github ...

**Comment by az0** [comment]
The instructions on the docs site suggest a package. The difference is it's
often newer

**Comment by Huluti** [comment]
No problem ;)

**Pull request closed without merging**
