### PR TITLE
Add OARS content rating, shorter screenshot caption

### PR DESCRIPTION
**Pull request by terrycloth**
Solves Issue #780.

...Technically, the screenshot taken from the website is for BleachBit 3.2, but the UI hasn't changed much in v4.x.

### CODE REVIEW

**Comment by abitrolly** [comment]
Isn't the dark mode the default?

**Comment by terrycloth** [comment]
> Isn't the dark mode the default?

Oh, right, yes, good point.

**Comment by abitrolly** [comment]
@terrycloth my though was that if the dark mode is the default, then the title can be shortened even more. )

**Comment by terrycloth** [comment]
My reasoning had been that since dark UI themes are relatively uncommon outside terminals and code editors, it was worth pointing that it's the default instead of... some random custom theme, or whatever. But I don't have strong feelings about the exact wording, as long as it's short enough to close issue #780.

**Pull request merged**
