### PR TITLE
Bring Maël Lavault's GTK3 port up to date

### PR DESCRIPTION
**Pull request by tstenner**
To do:
- [x] launching from CLI
- [x] shredding files via drag & drop
- [x] keep the windows installer small
- [x] test everything

### CODE REVIEW

**Comment by ROCKNROLLKID** [comment]
I see you put down "Keep the windows installer small".

Does that mean you will actually shrink everything down or do you mean the changes you do you will just try to keep small?

**Comment by az0** [comment]
@tstenner : Thank you for working on this. Even if not everything is all ready (like the small Windows installer), I would like to release an alpha version with binary packages for Windows and Linux

@ROCKNROLLKID : I am not sure him about him, but what I meant by a small Windows installer is modifying the standard Python plus GTK+ frozen runtime to make them smaller. That includes removing unneeded files and altering some other files. For example with the old installer I compressed the translation .pot files by removing unnecessary entries. I hope it does not require recompiling GTK+ from source code

**Comment by ROCKNROLLKID** [comment]
This is looking good so far. Keep up the good work!

**Comment by az0** [comment]
I really appreciate this hard work to update this.

Could we please merge this into a new branch for now? This will allow parallel testing, while GTK2 is stable. As I mentioned, I would like to release this like an alpha version sooner than later, even if the Windows installer is giant. Meanwhile I will avoid making changes to the GUI in GTK2 to avoid need for future remerging work.

**Comment by tstenner** [comment]
So far I haven't tested the UAC stuff on windows. I hope it works, but depending on how the GTK Application handles launching again / quitting it might not work. Could someone test this with python on windows?

**Comment by ROCKNROLLKID** [comment]
Another thing we might want to do is figure out how many XP users there are that use BleachBit, as GTK3 will drop support for XP.

If there is a lot, then I would suggest leaving other builds that are on GTK2 so XP users can use that.

**Comment by tstenner** [comment]
After some minor changes, this already starts on Windows. I still have to change the packaging and reintroduce the diagnostics dialog, but we could switch relatively soon after the next version comes out.

On an other note the coveralls comments really clutter the comments section, do we need them if we still have it in the checks section?

**Comment by az0** [comment]
Windows: it's good to hear about your progress.

Coveralls: I changed the the setting "Coverage Decrease Threshold for failure" from no tolerance to 1%, so that will usually make Coveralls less chatty. Here the -11.7% drop is apparently because the comparison is to the other branch. Otherwise, a -11.7% would be a good cause for alarm. If you merge commit 2ada424ef90b4dd3bc5147dd763896c5e1340865, it will increase coverage

**Comment by tstenner** [comment]
`strip`ing the binaries doesn't work right now, but the portable installation is only 13MB so it's not a high priority right now.
Could someone try it out and see if it works?

**Comment by ROCKNROLLKID** [comment]
If you could make a build for Windows, I would be willing to.

**Comment by tstenner** [comment]
Sorry, I forgot the link: https://ci.appveyor.com/api/buildjobs/tru33dahye6yxuo0/artifacts/BleachBit-1.17-portable.zip

**Comment by ROCKNROLLKID** [comment]
I downloaded it and put it to my desktop. I tried running as admin and non-admin, but it doesn't seem to want to start. Not even the console works, either. There is no error messages. I don't even see it load up in task manager.

**Comment by tstenner** [comment]
Huh, strange. `bleachbit.exe` should at least write a log file.

**Comment by ROCKNROLLKID** [comment]
I have checked all the folders in the BleachBit folder. There is no log file to be found.

**Comment by tstenner** [comment]
Is <a href="http://www.dependencywalker.com/">Dependency Walker</a> missing anything?

**Comment by ROCKNROLLKID** [comment]
Here is a report:

[bleachbit.zip](https://github.com/bleachbit/bleachbit/files/1051013/bleachbit.zip)

**Comment by tstenner** [comment]
I have pushed a <a href="https://ci.appveyor.com/api/buildjobs/1a9i97oyxhk2ycip/artifacts/BleachBit-1.17-portable.zip">build without UPX compression </a>, could you try that?
Also, do you get a UAC popup when starting it or simply nothing?

**Comment by ROCKNROLLKID** [comment]
The new build still isn't working for me. There is no UAC popup for me, either.

**Comment by tstenner** [comment]
It tried it on a blank windows 10 host without python or anything else installed and it ran just fine. I'll see if I can find a windows 7 machine somewhere.

**Comment by tstenner** [comment]
Also working on a clean Windows 7 machine. Does anyone have any ideas how to investigate this?

**Comment by ROCKNROLLKID** [comment]
My motherboard is coming on Friday. If my PC works, I will retest it on my PC. Currently on my laptop, but this laptop has issues at times.

**Comment by ROCKNROLLKID** [comment]
Alright, I just tested on my PC. It works there, but took a while to load (I have a SSD too). Other then that, it is working alright. Maybe a few tweaks here and there wouldn't hurt, either. The new GUI look is starting to look a little more modern (good thing) and a little less clutter.

**Comment by az0** [comment]
I merged it into a new branch, and I will take a closer look. I appreciate your help and patience.

**Pull request closed without merging**
