### PR TITLE
Python 3

### PR DESCRIPTION
**Pull request by mkhon**
Fix Python 3.7 tests

### CODE REVIEW

**Comment by az0** [comment]
Thanks for working on this, Max. The good news is Travis CI reports Python 3.7 works. 

However, Python 3.5 and Python 3.5 have errors.

**Comment by mkhon** [comment]
3.5 and 3.6 should be fixed now

**Comment by az0** [comment]
Yes, thank you.

**Comment by blacksong0194** [comment]
me presenta  solamente cuadros en la interfaz gráficas no tiene fuentes, osea no tiene letras solo cuadros
Anotación 2020-08-25 231123

**Comment by az0** [comment]
> me presenta solamente cuadros en la interfaz gráficas no tiene fuentes, osea no tiene letras solo cuadros

You have an issue with boxes replacing letters, but it is not directly related to the theme of issue 763, so your comment does not belong on this page. Also, it is a duplicate of https://github.com/bleachbit/bleachbit/issues/992 . Please do not post your same problem in two places. I replied to you under issue 992

**Pull request merged**
