### PR TITLE
Fix for 'Exclusion in winapp2.ini not honoured' (issue #1247)

### PR DESCRIPTION
**Pull request by livingentity**

### CODE REVIEW

**Comment by livingentity** [comment]
Only did some minor testing on the original issue [#1247](https://github.com/bleachbit/bleachbit/issues/1247) and a few other cases.

**Comment by livingentity** [comment]
Now that I think of it there's probably a much easier solution:
Just replace `parts = excludekey.split('|')` by `parts = excludekey.split(r'\\*\|')`.

**Comment by livingentity** [comment]
Tested with _all_ exclusion entries in the current winapp2.ini and it's fine.

However there's a different problem that file paths with square brackets don't work with regex because fnmatch.translate doesn't escape them.

But this can be merged, I guess.

**Comment by rados** [comment]
@livingentity 
Nice work, thank you. 

@az0 
Seems OK to me.

**Pull request merged**
