### PR TITLE
Suggested new parameters for 7-Zip

### PR DESCRIPTION
**Pull request by Tobias-B-Besemer**

### CODE REVIEW

**Comment by Tobias-B-Besemer** [comment]
@az0, guess before I make more tries with changes I'm not sure if they right and push more CI, you should finish this patch...

**Comment by Tobias-B-Besemer** [comment]
If the build script would work with my changes...

2019-09-10 07_38_03-I__work_Cleaner_CI_BleachBit-2 3 1257-portable_BleachBit-Portable

2019-09-10 07_38_57-I__work_Cleaner_CI

**Comment by az0** [comment]
library: py2exe expects a .zip, and I'm not sure how deep you'd have to dig in py2exe to change that. It would involve shipping 7zip, and that might eat up the benefit of 1345-811KB.

Portable: Many people don't have 7zip installed, and it's important to reduce the friction of installation to keep users happy. Also, once upx executable compression is re-enabled (it was disabled initially for GTK 3), the difference between .zip and .7z could considerably shrink.

**Comment by Tobias-B-Besemer** [comment]
What's about "7ZIP and UPX" at http://www.py2exe.org/index.cgi/BetterCompression? May this help or you doing it already?

**Comment by Tobias-B-Besemer** [comment]
Is Py2Exe only needed for the Portable Version? Here's a sample to create with Py2Exe and NSIS and 7-Zip a file http://www.py2exe.org/index.cgi/SingleFileExecutable...

**Comment by az0** [comment]
Like shown in the article, I already use 7zip to repack the library.zip

Like shown in the article, I used UPX to pack Windows executables. It was temporarily turned off for GTK 3 development. Last I checked, UPX with GTK 3 caused an application startup error. Here is a ticket https://github.com/bleachbit/bleachbit/issues/316

py2exe is used on Windows for both the installed and portable versions. All files are identical except for the NSIS installer and one `.ini` file.

**Pull request closed without merging**
