### PR TITLE
Fix #340 #558

### LINKED ISSUE #340: ascii decode error in full_path_decode when LANG=C
when `LANG=C`

````
======================================================================
ERROR: test_DeepScan (tests.TestDeepScan.DeepScanTestCase)
Unit test for class DeepScan.  Preview real files.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/TestDeepScan.py", line 88, in test_DeepScan
    for ret in ds.scan():
  File "bleachbit/DeepScan.py", line 104, in scan
    full_path = full_path.decode(bleachbit.FSE)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc9 in position 12: ordinal not in range(128)
````

### PR DESCRIPTION
**Pull request by rados**
This is a new PR that originates from PR #590, but now the Windows' test should be fixed.

### CODE REVIEW

**Comment by az0** [comment]
Thanks. I will check it out

**Comment by az0** [comment]
Regarding #340,  whether I am on the master branch or the branch with your fix, I get the same error

```
$ git checkout rados-fix_#340_#558 
Switched to branch 'rados-fix_#340_#558'

$ LANG=C python -m unittest tests.TestDeepScan.DeepScanTestCase
no default locale found.  Assuming 'C'
/tmp/DeepScanTestCaseP5hZ4h
.Delete 0 /tmp/DeepScanTestCaseP5hZ4h/foo.txt.bbtestbak
Delete 0 /tmp/DeepScanTestCaseP5hZ4h/sub/bar.ini.bbtestbak
Disk space recovered: 0
Files deleted: 2
.Es
======================================================================
ERROR: test_encoding (tests.TestDeepScan.DeepScanTestCase)
Test encoding
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/TestDeepScan.py", line 79, in test_encoding
    self._test_encoding(test)
  File "tests/TestDeepScan.py", line 47, in _test_encoding
    os.mkdir(subdir)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 28-29: ordinal not in range(128)

----------------------------------------------------------------------
Ran 4 tests in 0.926s

FAILED (errors=1, skipped=1)

```

**Comment by az0** [comment]
Thanks: I confirmed the fix for `set_environ(cd,...)`, but I can't merge that yet because it's combined with the other change that doesn't seem to work. In the future it would help to separate pull requests/commits.

**Comment by rados** [comment]
I think the nature of the issue in #340 is about failing test_DeepScan unit test which is fixed here. You can check with

 'LANG=C python -m unittest tests.TestDeepScan.DeepScanTestCase.test_DeepScan' 

Also please note that 'test_encoding' cannot pass with 'LANG=C' because it has some hard coded unicode paths in it. I am not sure why but seems like there should be a good reason. Maybe this could be extracted in a new ticket...

**Comment by az0** [comment]
Hmm, I can no longer reprodue #340 on my system with either the latest Git commit in the master branch or a commit from around the time I filed that, so let's say this is all fixed. I'll merge this PR into a temporary branch until milestone 1 is complete.

**Comment by az0** [comment]
Also, on my system this command works without the changes in the pull request...

`LANG=C python -m unittest tests.TestDeepScan.DeepScanTestCase.test_DeepScan`

**Comment by rados** [comment]
Just so you know, it fails without the changes here...

$ LANG=C python -m unittest tests.TestDeepScan.DeepScanTestCase.test_DeepScan
no default locale found.  Assuming 'C'
/tmp/DeepScanTestCaseLX0edv
E
======================================================================
ERROR: test_DeepScan (tests.TestDeepScan.DeepScanTestCase)
Unit test for class DeepScan.  Preview real files.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/TestDeepScan.py", line 90, in test_DeepScan
    for ret in ds.scan():
  File "bleachbit/DeepScan.py", line 105, in scan
    full_path = full_path.decode(bleachbit.FSE)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 21: ordinal not in range(128)

----------------------------------------------------------------------
Ran 1 test in 0.032s

FAILED (errors=1)

**Pull request closed without merging**
