### PR TITLE
Gtk3 fixes

### PR DESCRIPTION
**Pull request by mkhon**
- #313 - Drag and drop was actually working but it did not work if drop was performed on main textview (I fixed that)
- #545 
- shred by pasting from clipboard

### CODE REVIEW

**Comment by az0** [comment]
The drag-and-drop and "shred from clipboard" work OK on Ubuntu 18.10. Thank you.

First, please would you change it so it does not close the window except when using `--shred --gui` from the command line? In other words, any of these should not close the window: drag and drop, shred files from clipboard, and the regular cleaning button on the menu bar. 

Second, the GUI no longer starts on Windows 10 with GTK 3.18. It throws warnings (which I have not seen before) and then quits.

````
> bleachbit.py

** (python.exe:8920): WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

** (python.exe:8920): WARNING **: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'

** (python.exe:8920): WARNING **: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'
````

**Comment by mkhon** [comment]
1) Can you clarify about closing the window? It does not close the window when I do drag and drop or shred and also cleaning button - tested on Windows 10 (GTK 3.18) and Ubuntu 18.04 LTS

2) Again, I did all the implementation and testing on Windows 10 + GTK 3.18 and I do not see these messages on start.

**Comment by mkhon** [comment]
Screen Shot 2019-04-29 at 12 31 34

**Comment by mkhon** [comment]
May be the problem is that I was testing with --gui --no-uac - DND does not work for me if UAC is done, however the app still starts up properly.

**Comment by az0** [comment]
You were right: rebooting Windows 10 fixed the issue that BleachBit did not start. It starts fine now.

Yes, Windows does not allow DND with elevated permissions, so that is why I added "shred paths from clipboard."

About the window closing: I see this on Ubuntu 18.10 but not on Windows 10. When I preview some items, it does not close. After cleaning anything, it closes.
Here is a video https://youtu.be/Pm35I0oG9zE

**Comment by mkhon** [comment]
Hmm, it does not happen for me in Ubuntu 18.04 and Windows 10 + GTK 3.18. I will try to see what happens on 18.10.

Does it happen on bleachbit gtk3 branch? Can you run "git bisect" from bleachbit gitk3 HEAD (rev. d5ab76fd71698d3170e58ed53c3129f86dbd399c). None of my last three commits can theoretically cause this.

**Comment by mkhon** [comment]
I can not reproduce automatic quite (after clean) on Ubuntu 18.10 as well.

**Comment by az0** [comment]
The "closing" issue was my fault. Thanks for your patience.

**Pull request merged**
