### PR TITLE
teamviewer.xml

### PR DESCRIPTION
**Pull request by Tobias-B-Besemer**
Why "Can’t automatically merge." ??? I should be sync...

### CODE REVIEW

**Comment by Tobias-B-Besemer** [comment]
New PR ???

**Comment by az0** [comment]
It looks like the PR here is similar to your change I already commited: https://github.com/bleachbit/bleachbit/commit/b6ef19f94575f1ce88018f4f0620a705b2034cde

Notice some of the "old" lines are the same in both commits. This means the new PR is branched from an earlier commit, but  it's trying to change the same lines of code. In other words, the new PR is not starting from after the previous commit. It's sort of like traveling back in time.

**Comment by Tobias-B-Besemer** [comment]
I always need to switch to Master to make a new branch... Maybe I forgot and made the branch from a other branch... :-/

**Comment by az0** [comment]
I am closing this because it seems to be replaced by https://github.com/bleachbit/bleachbit/pull/498

**Comment by Tobias-B-Besemer** [comment]
Yes, thx!

**Pull request closed without merging**
