### PR TITLE
Update Slovak translation

### PR DESCRIPTION
**Pull request by jose1711**

### CODE REVIEW

**Comment by az0** [comment]
Thank you for the translations. If I accept this pull request, then all your changes will get overwritten the next time I update the translations from the master system, so it would be best if you would put your translations there. Here's a link https://www.bleachbit.org/contribute/translate

**Comment by Tobias-B-Besemer** [comment]
@jose1711, have you contributed your translations in an other way ???
You can also help to make the Slovak translation complete...
Here is IMHO a better link for you: https://translations.launchpad.net/bleachbit/trunk/+pots/bleachbit/sk/+translate

**Comment by Tobias-B-Besemer** [comment]
I have downloaded the file sk.po and uploaded it on Launchpad...
@az0, this should work, or ???

2019-11-06 07_32_29-Upload translation _ Slovak (sk) _ Template “bleachbit” _ Series trunk _ Transla

**Comment by Tobias-B-Besemer** [comment]
Import queue: https://translations.launchpad.net/bleachbit/trunk/+imports

**Comment by Tobias-B-Besemer** [comment]
:)

**Comment by Tobias-B-Besemer** [comment]
:)

Screenshot_20191106-095921_Gmail

**Comment by jose1711** [comment]
thank you all

**Comment by Tobias-B-Besemer** [comment]
You're welcome! :-)

Do you like to help to translate the rest of BB into Slovak in Lauchpad ???

**Comment by jose1711** [comment]
> Do you like to help to translate the rest of BB into Slovak in Lauchpad ???

truth be told my todo list is enormously long so no real plans for now.

**Comment by Tobias-B-Besemer** [comment]
OK, maybe a other day... Thank you anyway for your work! :-)

**Pull request closed without merging**
