### PR TITLE
Minor updates to Desktop Entry and AppStream metadata

### PR DESCRIPTION
**Pull request by terrycloth**
This is maybe just a little pedantic, but I'm rewriting the RPM spec for BleachBit for Fedora, so it's relevant to me. And this pull request will bring these two files in line with the current specifications.

See the commit comments. Let me know if you have any questions :)

### CODE REVIEW

**Comment by terrycloth** [comment]
I wondered briefly about also adding more screenshots -- perhaps the Chaff feature in action? -- but I dunno, BleachBit is largely text-based, and I wound up just using the one current screenshot that's on the website.

**Comment by az0** [comment]
> I wondered briefly about also adding more screenshots -- perhaps the Chaff feature in action? -- but I dunno, BleachBit is largely text-based, and I wound up just using the one current screenshot that's on the website.

There are some on the [screenshots page ](https://www.bleachbit.org/screenshots), but now that I look at it, it could use updating.


> This is maybe just a little pedantic, 

A pedantic PR can be OK, especially if it's easy to review and merge.

> but I'm rewriting the RPM spec for BleachBit for Fedora, so it's relevant to me. And this pull request will bring these two files in line with the current specifications.

Perhaps you could take a look at the [bleachbit.spec](https://github.com/bleachbit/bleachbit/blob/master/bleachbit.spec) that I use on [OpenSUSE Build Service](https://build.opensuse.org/package/show/home:andrew_z/bleachbit)? Fedora 28 builds, but Fedora 29-31 fail. Fedora 29 has this error:

>/var/tmp/rpm-tmp.rZABtM: line 31: /usr/bin/python: No such file or directory

I assume I am missing a build dependency.

**Comment by terrycloth** [comment]
Thanks for all your hard work :)

> Perhaps you could take a look at the bleachbit.spec that I use on OpenSUSE Build Service?

Sure, I can take a look. I'll open an issue with notes, or a pull request with a fix, after the weekend.

**Comment by az0** [comment]
@terrycloth 
two FYIs

First, I fixed the builds for Fedora 30 and 31. However, it seems CentOS 8 doesn't provide python2, so it won't build. Still, I welcome any advice for the `.spec` file

Second, this PR broke the `Makefile` because of the rename, so `make install` does not work. I will fix it

**Comment by AsciiWolf** [comment]
There seem to be some minor issues:
```
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
• style-invalid         : <caption> is too long [BleachBit 3.0 in dark mode showing discovered Google Chrome files];longest allowed is 50 chars
```

Otherwise looks good, thanks!

**Comment by az0** [comment]
> There seem to be some minor issues:
> 
> ```
> • tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
> • style-invalid         : <caption> is too long [BleachBit 3.0 in dark mode showing discovered Google Chrome files];longest allowed is 50 chars
> ```
@AsciiWolf  

> Otherwise looks good, thanks!

This PR was merged and release for BleachBit 3.2, so please either open a new issue or a new pull request.

**Pull request merged**
