### PR TITLE
added windows crashdumps cleaner

### PR DESCRIPTION
**Pull request by cfoellmann**
UNTESTED!!
havent had the time to look into how to compile, yet. @az0 can you test that one?

### CODE REVIEW

**Comment by ROCKNROLLKID** [comment]
There is a entry in Winapp2 that looks very similar to this:

[Memory Dumps]
ID=1015
LangSecRef=3021
FileKey1=%windir%|memory.dmp
FileKey2=%windir%\MiniDump|*.dmp
FileKey3=%LocalAppData%\CrashDumps|*.dmp

This was one of the entries taken out of Winapp2 and was re-added to BleachBit specifically. I suppose we can move it to CleanerML, but then I suggest you add the other FileKeys and then remove it from Winapp2.

**Comment by cfoellmann** [comment]
What can we do here?
Move the OS (Windows) cleaners over to CleanerML? Or extend the core files?

**Comment by ROCKNROLLKID** [comment]
Since it is no longer under Winapp2 care, I would suggest moving it to CleanerML.

**Comment by cfoellmann** [comment]
Winapp2 was Never more than an option for bleachbit.
Currently the cleaners for win are in the bleachbit package - hardcoded.

**Comment by ROCKNROLLKID** [comment]
Feel free to take any extra entries from the Winapp2 one and move it to your CleanerML and I will edit the Winapp2 file here on github and remove the entry out of there.

I think it should be done to all the entries that got removed from Winapp2 that we re-added in a modified copy of Winapp2. They should all be in CleanerML instead.

**Comment by az0** [comment]
Yes, it looks like this could be a simple cleaner written in CleanerML. Because it affects so many Windows systems, though, I would like to merge it in this repository instead.

If the cleaner were named windows.xml, it would be a good place to move more of the cleaning options out of Python and into CleanerML.

In case you like to take to attempt it, I will leave this PR open.

**Comment by ProactiveServices** [comment]
As someone who fixes Windows systems for a living I'd ask that you only take out dumps that are old, say at least a year old.

**Comment by ROCKNROLLKID** [comment]
This pull request is not needed anymore. The removed entries have been moved back to the main Winapp2 respo and are managed by the community again. See here: https://github.com/MoscaDotTo/Winapp2/tree/master/Non-CCleaner

You can go ahead and close this.

**Comment by az0** [comment]
Closing because of comment "This pull request is not needed anymore. "

**Pull request closed without merging**
