### PR TITLE
Replace for loops with comprehensions and simplify existing comprehensions

### PR DESCRIPTION
**Pull request by monosans**

### CODE REVIEW

**Comment by az0** [comment]
I would like to give this a closer look after merging Max's change for issue 848. He's recently made a lot of progress on it

**Comment by abitrolly** [comment]
#848

**Comment by az0** [comment]
The other day, Max let me know that for #848 
>BleachBit changes are minimal so far (mostly to windows/setup_py2exe.py)

19 hours ago, AppVeyor reported this error ([log](https://ci.appveyor.com/project/az0/bleachbit/builds/40424801))
```
======================================================================
ERROR: tests.TestNsisUtilities (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python34\lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "c:\python34\lib\unittest\case.py", line 580, in run
    testMethod()
  File "c:\python34\lib\unittest\loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: tests.TestNsisUtilities
Traceback (most recent call last):
  File "c:\python34\lib\unittest\loader.py", line 323, in _find_tests
    module = self._get_module_from_name(name)
  File "c:\python34\lib\unittest\loader.py", line 301, in _get_module_from_name
    __import__(name)
  File "C:\projects\bleachbit\tests\TestNsisUtilities.py", line 184
    *['{}.{}'.format('ddd', ext) for ext in _REBOOTOK_FILE_EXTENSIONS],
               ^
SyntaxError: can use starred expression only as assignment target
----------------------------------------------------------------------
Ran 209 tests in 133.396s
FAILED (errors=1, skipped=34)
```

**Comment by monosans** [comment]
```
> SyntaxError: can use starred expression only as assignment target
```
This happens because Python version is lower than 3.5.

**Comment by az0** [comment]
> > SyntaxError: can use starred expression only as assignment target
> 
> @az0, this happens because Python version is lower than 3.5.

Python 3.4 is required until https://github.com/bleachbit/bleachbit/issues/848 is fixed, and the update is not trivial because of  pywin32 and GTK on Windows

**Comment by monosans** [comment]
@az0 seems like everything is fine. CI fail is not related to this changes.

**Pull request merged**
