### PR TITLE
vlc.xml: running type="exe" from os="linux" to os="unix"

### PR DESCRIPTION
**Pull request by Tobias-B-Besemer**
Have a look at https://github.com/bleachbit/bleachbit/pull/699 because of the second file.

### CODE REVIEW

**Comment by Tobias-B-Besemer** [comment]
Uh! Saw ATM that this cleaner requires maybe some clarification...
There is no os="linux, windows" in it...
First question: Is set os="linux, windows" possible ???
(Note: I should not the answer in the doc...)
ATM this cleaner should get executed on UNIX systems, too...
...but <var name="Profile"> & <var name="Config-File"> have only os="windows" & os="linux"...
...so I think this cleaner gets shown and executed on UNIX systems, too, but do nothing... Right ???
Think I/we should fix that...

**Comment by Tobias-B-Besemer** [comment]
@az0, have in this PR UAC.nsh in... 'cause of .gitattributes...
I will close this PR now... make a new one later...
...but I think we should discuss the UNIX prob before here...

**Comment by az0** [comment]
> There is no os="linux, windows" in it...
> First question: Is set os="linux, windows" possible ???

I don't see that it's necessary. The way it's coded now already does what I think you want. 

> ATM this cleaner should get executed on UNIX systems, too...

You mean chage linux to unix? OK.

**Comment by Tobias-B-Besemer** [comment]
> You mean chage linux to unix? OK.

Thought this was what I did... ^^

...OK, not everywhere! So I make a new PR...

**Pull request closed without merging**
