### PR TITLE
Updated and improved Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
:-)

### CODE REVIEW

**Comment by az0** [comment]
@Vistaus 
Thank you kindly for the new translation. The way translations are managed for this project is a one way sync between Launchpad and GitHub. If I were to accept this pull request, it would be overwritten with the next change on Launchpad, so would you please upload it there?

General information about translating this project: https://www.bleachbit.org/contribute/translate

Direct link to Dutch translation: https://translations.launchpad.net/bleachbit/trunk/+pots/bleachbit/nl/+translate

The second link accepts uploads in .po format, if you started with the .po file exported from Launchpad (which is the same as in GitHub).

**Comment by Vistaus** [comment]
Alright, done.

**Comment by az0** [comment]
Great. I merged it.

**Comment by Vistaus** [comment]
@az0 Thank you! :)

**Pull request closed without merging**
