### PR TITLE
Fix #567

### LINKED ISSUE #567: Error when enabling options that show a pop-up warning
Windows 8 SL 64 bit
Run bleachbit.exe as administrator. Impossible to mark many points. Here is what can be marked.
<a href='https://postimg.cc/1fMdCNz2' target='_blank'></a>
<a href='https://postimg.cc/8jT3mbTL' target='_blank'></a>
[bleachbit.exe.log](https://github.com/bleachbit/bleachbit/files/3317252/bleachbit.exe.log)
[BleachBit.ini.txt](https://github.com/bleachbit/bleachbit/files/3317253/BleachBit.ini.txt)

### PR DESCRIPTION
**Pull request by rados**
The user that reported the issue had two problems - one with checking unicode three nodes and second that the main app menu showed utf-8 errors. The second problem has been fixed with commit with message "Gtk.Builder uses system dgettext() for "translatable" items." Here I am merging the fix for the checkboxes which has been already verified by the user. We can give him a build to verify both issues fixed.

### CODE REVIEW

**Comment by az0** [comment]
I will take a look

**Comment by az0** [comment]
@rados 
The user ediowar tested and replied
>Invalid UTF-8 fixed. Still errors:
Ошибка во время выполнения операции 'firefox': 'cannot import name _common'
Ошибка во время выполнения операции 'windows_explorer': ''ascii' codec can't encode characters in position 55-65: ordinal not in range(128)'
Ошибка во время выполнения операции 'skype': 'cannot import name _common'



Feel free to communicate directly with this users (and users on other issues), if you like

**Comment by rados** [comment]
@az0 
Just pushed a fix for this error (which basically fixes #533 as well because it is the same issue): 

Ошибка во время выполнения операции 'windows_explorer': ''ascii' codec can't encode characters in position 55-65: ordinal not in range(128)'

For the  'cannot import name _common' part as far as my short check and research showed there could be something in the build itself. I can reproduce it from the custom build given to user but cannot reproduce it from source code. I know, I have to learn how to build locally and trace it, but does this time come?

**Comment by az0** [comment]
The traceback for `cannot import name _common` come from what seems to be an unrelated part of the code. (It's the same DLL issue as #589.) Let's consider #567 fixed.

**Comment by rados** [comment]
Okay, thanks. Just to add that I started to create a test for this part 'characters in position 55-65: ordinal not in range(128)' and will give it to you soon.

**Pull request merged**
