### PR TITLE
NSIS.MUI2.Remove-ANSI (Review wanted!)

### PR DESCRIPTION
**Pull request by Tobias-B-Besemer**

### CODE REVIEW

**Comment by az0** [comment]
The changes to `windows/bleachbit.nsi` look OK, but there are many other changes mixed in

**Comment by Tobias-B-Besemer** [comment]
This was the encoding error after introduce of ".gitattributes". The changes you already exepted in the other PR. So this PR change now only bleachbit.nsi.

**Comment by Tobias-B-Besemer** [comment]
I try to fix the PR...

**Comment by Tobias-B-Besemer** [comment]
Now it looks good, again! ;)

**Comment by Tobias-B-Besemer** [comment]
Thx for landing! :)

**Pull request merged**
