### PR TITLE
Py3

### PR DESCRIPTION
**Pull request by TraistaRafael**
I try to set application's theme to windows 10 on windows hosts, I made the changes on an ubuntu machine and I prepared a development commit with many logs to see if I can get the theme shipped in the win exe.

### CODE REVIEW

**Comment by az0** [comment]
Thanks for your effort. I tried the 1510 build from AppVeyor on WIndows 10.

The theme looks the same, and the console has this



```
C:\Users\user>C:\Users\user\Downloads\BleachBit-3.1.0.1510-portable\BleachBitPortable\bleachbit_console.exe --gui --no-uac
Test build
Apply windows 10 theme
bleachbit_exe_path exe path is missing, set now paths
sys.executable: C:\Users\user\Downloads\BleachBit-3.1.0.1510-portable\BleachBit-Portable
exe path: C:\Users\user\Downloads\BleachBit-3.1.0.1510-portable\BleachBit-Portable\themes\windows10\gtk.css
Exe theme found
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\GUI.py", line 315, in do_startup
  File "C:\projects\bleachbit\bleachbit\GUI.py", line 117, in build_app_menu
GLib.Error: gtk-css-provider-error-quark: gtk-contained.css:21:21'-gtk-outline-radius' is not a valid property name (3)
```

**Comment by TraistaRafael** [comment]
Hi, I had the same error, the theme is not compatible with the gtk version. I resolved by replacing the theme directly in the installer with a new one I found online. I will prepare another build with the compatible win10 theme.

**Comment by TraistaRafael** [comment]
The latest build (https://ci.appveyor.com/project/az0/bleachbit/builds/30778341) should have the compatible windows10 theme integrated. I tested on my device.

**Comment by az0** [comment]
You marked this as a work in progress. Do you think it's ready?

It works, though the theme itself is "rough" in the sense that the toolbar buttons have a fuzzy appearance. This issue is beyond the scope of our contract, though, so I'm not asking you to fix it.

2020-02-16 Windows theme

**Pull request merged**
